### ISSUE TITLE
All items in the player's inventory that can store things was disappeared

### ISSUE THREAD

**Issue by yahinstudio** [MilSpecSG/MSDataSync#6]
This plugin seems to cause all items in the player's inventory that can store things to disappear.
Such as extrabotany:masterhandbag and minecraft:white_shulker_box.
help!

**Comment by jacoballen1** [comment]
This is being worked on, be on the lookout for a new version in the near future.
Note: The release won't be public until the api Anvil is published.

**Comment by alexstaeding** [comment]
This should be fixed in latest version. Please update to [v0.7.0](https://ore.spongepowered.org/AnvilPowered/DataSync/versions/0.7.0) and try again. Note that this version requires Anvil [v0.2.0](https://ore.spongepowered.org/AnvilPowered/Anvil/versions/0.2.0). Make sure you rename your old data directory because the new data format is not compatible with the old one.
